-- MySQL Script generated by MySQL Workbench
-- Mon Mar  1 16:31:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`BANK_USER_STATUS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_USER_STATUS` (
  `status_id` INT NOT NULL,
  `status_name` VARCHAR(300) NOT NULL,
  `status_descrip` LONGTEXT NULL,
  PRIMARY KEY (`status_id`),
  UNIQUE INDEX `status_id_UNIQUE` (`status_id` ASC) VISIBLE,
  UNIQUE INDEX `status_name_UNIQUE` (`status_name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_USER` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(50) NOT NULL,
  `user_surname` VARCHAR(50) NOT NULL,
  `user_patronymic` VARCHAR(50) NOT NULL,
  `user_login` VARCHAR(30) NOT NULL,
  `user_password` VARCHAR(60) NOT NULL,
  `user_age` DATETIME NOT NULL,
  `user_status_to_system` INT NOT NULL,
  `user_register_data` DATETIME NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_login_UNIQUE` (`user_login` ASC) VISIBLE,
  INDEX `user_status_to_system_idx` (`user_status_to_system` ASC) VISIBLE,
  CONSTRAINT `user_status_to_system`
    FOREIGN KEY (`user_status_to_system`)
    REFERENCES `mydb`.`BANK_USER_STATUS` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_USER_ACCESS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_USER_ACCESS` (
  `access_id` INT NOT NULL,
  `access_user_status` INT NOT NULL,
  `access_name_table` VARCHAR(350) NOT NULL,
  `access_modification` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`access_id`),
  UNIQUE INDEX `access_id_UNIQUE` (`access_id` ASC) VISIBLE,
  INDEX `access_user_status_idx` (`access_user_status` ASC) VISIBLE,
  CONSTRAINT `access_user_status`
    FOREIGN KEY (`access_user_status`)
    REFERENCES `mydb`.`BANK_USER_STATUS` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_CURRENCY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_CURRENCY` (
  `currency_id` INT NOT NULL,
  `currency_name` VARCHAR(100) NULL,
  `currency_dollar` INT NOT NULL,
  `currency_euro` INT NOT NULL,
  `currency_rub` INT NOT NULL,
  PRIMARY KEY (`currency_id`),
  UNIQUE INDEX `currency_id_UNIQUE` (`currency_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_CLIENT_COMPANY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_CLIENT_COMPANY` (
  `cl_comp_id` INT NOT NULL,
  `cl_comp_name` VARCHAR(100) NOT NULL,
  `cl_comp_descr` LONGTEXT NULL,
  PRIMARY KEY (`cl_comp_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_CLIENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_CLIENT` (
  `client_id` INT NOT NULL,
  `client_name` VARCHAR(50) NOT NULL,
  `client_surname` VARCHAR(50) NOT NULL,
  `client_patronymic` VARCHAR(50) NOT NULL,
  `client_company` INT NULL,
  `client_login` VARCHAR(30) NOT NULL,
  `client_password` VARCHAR(60) NOT NULL,
  `client_register_data` DATETIME NOT NULL,
  PRIMARY KEY (`client_id`),
  UNIQUE INDEX `client_id_UNIQUE` (`client_id` ASC) VISIBLE,
  UNIQUE INDEX `client_login_UNIQUE` (`client_login` ASC) VISIBLE,
  INDEX `client_company_idx` (`client_company` ASC) VISIBLE,
  CONSTRAINT `client_company`
    FOREIGN KEY (`client_company`)
    REFERENCES `mydb`.`BANK_CLIENT_COMPANY` (`cl_comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_ACTIVE_AUTHORIZED_CAPITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_ACTIVE_AUTHORIZED_CAPITAL` (
  `aac_id` INT NOT NULL,
  `aac_name_transactions` VARCHAR(500) NOT NULL,
  `aac_describtion_transactions` LONGTEXT NULL,
  `aac_debit` DECIMAL NOT NULL,
  `aac_credit` DECIMAL NOT NULL,
  `aac_type` INT NOT NULL,
  PRIMARY KEY (`aac_id`),
  INDEX `aac_type_idx` (`aac_type` ASC) VISIBLE,
  CONSTRAINT `aac_type`
    FOREIGN KEY (`aac_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_ACTIVE_CAMP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_ACTIVE_CAMP` (
  `acamp_id` INT NOT NULL,
  `acamp_name` VARCHAR(250) NOT NULL,
  `acamp_quantity` DECIMAL NOT NULL,
  `acamp_type` INT NOT NULL,
  PRIMARY KEY (`acamp_id`),
  INDEX `acamp_type_idx` (`acamp_type` ASC) VISIBLE,
  CONSTRAINT `acamp_type`
    FOREIGN KEY (`acamp_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_ACTIVE_DOCS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_ACTIVE_DOCS` (
  `docs_id` INT NOT NULL,
  `docs_name` VARCHAR(250) NOT NULL,
  `docs_type_doc` VARCHAR(45) NOT NULL,
  `docs_cash` DECIMAL NOT NULL,
  `docs_type` INT NOT NULL,
  PRIMARY KEY (`docs_id`),
  INDEX `docs_type_idx` (`docs_type` ASC) VISIBLE,
  CONSTRAINT `docs_type`
    FOREIGN KEY (`docs_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_ACTIVE_CREDITS_OUT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_ACTIVE_CREDITS_OUT` (
  `co_id` INT NOT NULL,
  `co_name` VARCHAR(100) NOT NULL,
  `co_describ` LONGTEXT NULL,
  `co_debtor` INT NOT NULL,
  `co_cash` DECIMAL NOT NULL,
  `co_type` INT NOT NULL,
  PRIMARY KEY (`co_id`),
  INDEX `co_debtor_idx` (`co_debtor` ASC) VISIBLE,
  INDEX `co_type_idx` (`co_type` ASC) VISIBLE,
  CONSTRAINT `co_debtor`
    FOREIGN KEY (`co_debtor`)
    REFERENCES `mydb`.`BANK_CLIENT` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `co_type`
    FOREIGN KEY (`co_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_ACTIVE_DEPOSITS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_ACTIVE_DEPOSITS` (
  `act_deposit_id` INT NOT NULL,
  `act_deposit_name` VARCHAR(250) NOT NULL,
  `act_deposit_cash` DECIMAL NOT NULL,
  `act_deposit_type` INT NOT NULL,
  PRIMARY KEY (`act_deposit_id`),
  UNIQUE INDEX `act_deposit_id_UNIQUE` (`act_deposit_id` ASC) VISIBLE,
  INDEX `act_deposit_id _idx` (`act_deposit_type` ASC) VISIBLE,
  CONSTRAINT `act_deposit_id `
    FOREIGN KEY (`act_deposit_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_ACTIVE_ASSET`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_ACTIVE_ASSET` (
  `ass_id` INT NOT NULL,
  `ass_name` VARCHAR(250) NOT NULL,
  `ass_cash` DECIMAL NOT NULL,
  `ass_type` INT NOT NULL,
  PRIMARY KEY (`ass_id`),
  UNIQUE INDEX `ass_id_UNIQUE` (`ass_id` ASC) VISIBLE,
  INDEX `ass_cash_idx` (`ass_type` ASC) VISIBLE,
  CONSTRAINT `ass_type`
    FOREIGN KEY (`ass_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_ACTIVE_DEBIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_ACTIVE_DEBIT` (
  `cdebit_id` INT NOT NULL,
  `cdebit_name` VARCHAR(250) NOT NULL,
  `cdebit_lender` INT NOT NULL,
  `cdebit_debit` DECIMAL NOT NULL,
  `cdebit_type` INT NOT NULL,
  PRIMARY KEY (`cdebit_id`),
  UNIQUE INDEX `cdebit_id_UNIQUE` (`cdebit_id` ASC) VISIBLE,
  INDEX `cdebit_type_idx` (`cdebit_type` ASC) VISIBLE,
  INDEX `cdebit_lender_idx` (`cdebit_lender` ASC) VISIBLE,
  CONSTRAINT `cdebit_lender`
    FOREIGN KEY (`cdebit_lender`)
    REFERENCES `mydb`.`BANK_CLIENT` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cdebit_type`
    FOREIGN KEY (`cdebit_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_PASSIVE_AUTHORIZED_CAPITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_PASSIVE_AUTHORIZED_CAPITAL` (
  `apc_id` INT NOT NULL,
  `apc_name_transactions` VARCHAR(250) NOT NULL,
  `apc_describtion_transactions` LONGTEXT NOT NULL,
  `apc_debit` DECIMAL NOT NULL,
  `apc_credit` DECIMAL NOT NULL,
  `apc_type` INT NOT NULL,
  PRIMARY KEY (`apc_id`),
  UNIQUE INDEX `apc_id_UNIQUE` (`apc_id` ASC) VISIBLE,
  INDEX `apc_type_idx` (`apc_type` ASC) VISIBLE,
  CONSTRAINT `apc_type`
    FOREIGN KEY (`apc_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_PASSIVE_CAMP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_PASSIVE_CAMP` (
  `pcamp_id` INT NOT NULL,
  `pcamp_name` VARCHAR(100) NOT NULL,
  `pcamp_quantity` DECIMAL NOT NULL,
  `pcamp_type` INT NOT NULL,
  PRIMARY KEY (`pcamp_id`),
  UNIQUE INDEX `pcamp_id_UNIQUE` (`pcamp_id` ASC) VISIBLE,
  INDEX `pcamp_type_idx` (`pcamp_type` ASC) VISIBLE,
  CONSTRAINT `pcamp_type`
    FOREIGN KEY (`pcamp_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_PASSIVE_ADD_CAPITAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_PASSIVE_ADD_CAPITAL` (
  `addc_id` INT NOT NULL,
  `addc_name` VARCHAR(250) NOT NULL,
  `addc_descrip` LONGTEXT NOT NULL,
  `addc_debit` DECIMAL NOT NULL,
  `addc_credit` DECIMAL NOT NULL,
  `addc_type` INT NOT NULL,
  PRIMARY KEY (`addc_id`),
  UNIQUE INDEX `addc_id_UNIQUE` (`addc_id` ASC) VISIBLE,
  INDEX `apc_type_idx` (`addc_type` ASC) VISIBLE,
  CONSTRAINT `apc_type`
    FOREIGN KEY (`addc_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_PASSIVE_CORRES_ACCOUTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_PASSIVE_CORRES_ACCOUTS` (
  `ca_bank_id` INT NOT NULL,
  `ca_bank_name` VARCHAR(250) NOT NULL,
  `ca_bank_company` INT NOT NULL,
  `ca_bank_cash` DECIMAL NOT NULL,
  `ca_bank_type` INT NOT NULL,
  PRIMARY KEY (`ca_bank_id`),
  UNIQUE INDEX `ca_bank_id_UNIQUE` (`ca_bank_id` ASC) VISIBLE,
  INDEX `ca_bank_company_idx` (`ca_bank_company` ASC) VISIBLE,
  INDEX `ca_bank_type_idx` (`ca_bank_type` ASC) VISIBLE,
  CONSTRAINT `ca_bank_company`
    FOREIGN KEY (`ca_bank_company`)
    REFERENCES `mydb`.`BANK_CLIENT_COMPANY` (`cl_comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ca_bank_type`
    FOREIGN KEY (`ca_bank_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_PASSIVE_DEPOSITS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_PASSIVE_DEPOSITS` (
  `pas_deposit_id` INT NOT NULL,
  `pas_deposit_name` VARCHAR(250) NOT NULL,
  `pas_deposit_cash` DECIMAL NOT NULL,
  `pas_deposit_type` INT NOT NULL,
  PRIMARY KEY (`pas_deposit_id`),
  UNIQUE INDEX `pas_deposit_id_UNIQUE` (`pas_deposit_id` ASC) VISIBLE,
  INDEX `pas_deposit_type_idx` (`pas_deposit_type` ASC) VISIBLE,
  CONSTRAINT `pas_deposit_type`
    FOREIGN KEY (`pas_deposit_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANK_PASSIVE_CREDIT_DEBIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANK_PASSIVE_CREDIT_DEBIT` (
  `cdebit_id` INT NOT NULL,
  `cdebit_name` VARCHAR(250) NOT NULL,
  `cdebit_lender` INT NOT NULL,
  `cdebit_cash` DECIMAL NOT NULL,
  `cdebit_type` INT NOT NULL,
  PRIMARY KEY (`cdebit_id`),
  UNIQUE INDEX `cdebit_id_UNIQUE` (`cdebit_id` ASC) VISIBLE,
  INDEX `cdebit_type_idx` (`cdebit_type` ASC) VISIBLE,
  INDEX `cdebit_lender_idx` (`cdebit_lender` ASC) VISIBLE,
  CONSTRAINT `cdebit_type`
    FOREIGN KEY (`cdebit_type`)
    REFERENCES `mydb`.`BANK_CURRENCY` (`currency_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cdebit_lender`
    FOREIGN KEY (`cdebit_lender`)
    REFERENCES `mydb`.`BANK_CLIENT` (`client_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
