CREATE TABLE BANK_PASSIVE_AUTHORIZED_CAPITAL
(
	apc_id INT PRIMARY KEY IDENTITY(1,1),
	apc_name_transactions NVARCHAR(250) NOT NULL,
	apc_describtion_transactions NVARCHAR(MAX) NOT NULL,
	apc_debit DECIMAL(10, 2),
	apc_credit DECIMAL,
	apc_type INT FOREIGN KEY REFERENCES BANK_CURRENCY(currency_id)
);

CREATE TABLE BANK_PASSIVE_CAMP
(
	pcamp_id INT PRIMARY KEY IDENTITY(1,1),
	pcamp_name NVARCHAR(250) NOT NULL,
	pcamp_quantity DECIMAL(10,2) NOT NULL,
	pcamp_type INT FOREIGN KEY REFERENCES BANK_CURRENCY(currency_id)
);

use BANK

CREATE TABLE BANK_PASSIVE_ADD_CAPITAL
(
	addc_id INT PRIMARY KEY IDENTITY(1,1),
	addc_name NVARCHAR(250) NOT NULL,
	addc_descrip NVARCHAR(MAX) NOT NULL,
	addc_debit DECIMAL(10, 2) NOT NULL,
	addc_credit DECIMAL(10, 2) NOT NULL,
	addc_type INT FOREIGN KEY REFERENCES BANK_CURRENCY(currency_id) NOT NULL,
);

CREATE TABLE BANK_PASSIVE_CORRES_ACCOUTS
(
	ca_bank_id INT PRIMARY KEY IDENTITY(1,1),
	ca_bank_name NVARCHAR(250) NOT NULL,
	ca_bank_company INT FOREIGN KEY REFERENCES BANK_CLIENT(client_id) NOT NULL,
	ca_bank_cash DECIMAL(10, 2) NOT NULL,
	ca_bank_type INT FOREIGN KEY REFERENCES BANK_CURRENCY(currency_id) NOT NULL,
);
